# Generated by Django 5.2.12 on 2026-05-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade')),
                ('unit_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Preco unitario')),
                ('subtotal', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Preco unitario')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'verbose_name_plural': 'Itens de pedido',
                'ordering': ['id'],
            },
        ),
    ]
