# Generated by Django 5.2.12 on 2026-04-27 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
                ('salary', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Preco unitario')),
                ('position', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['id'],
            },
            bases=('persons.person',),
        ),
    ]
