# Generated by Django 5.2.12 on 2026-04-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socialnetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('content_type', models.TextField(max_length=100, verbose_name='Tipo de conteúdo')),
                ('url', models.CharField(max_length=200, verbose_name='URL da Rede Social')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['id'],
            },
        ),
    ]
